In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [16]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10,activation='softmax')
])

In [12]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [13]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 1.4834 - accuracy: 0.9812
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 1.4805 - accuracy: 0.9836
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 1.4799 - accuracy: 0.9834
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 1.4786 - accuracy: 0.9850
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 1.4781 - accuracy: 0.9849


In [14]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 1.4838 - accuracy: 0.9786


[1.4837640523910522, 0.978600025177002]

In [17]:
model(x_train[:1]).numpy()

array([[ 0.6911334 , -0.07664131,  0.65742564, -0.433013  , -0.39630046,
         0.5382088 ,  0.16421244, -0.16655259,  0.36529014, -0.38837862]],
      dtype=float32)

In [18]:
model.predict(x_train[:1])

array([[ 0.6911334 , -0.07664131,  0.65742564, -0.433013  , -0.39630046,
         0.5382088 ,  0.16421244, -0.16655259,  0.36529014, -0.38837862]],
      dtype=float32)

In [20]:
class Cat():
    def __inti__(self):
        pass
    def speak(self):
        print("I'm a cat.")
        
class Blackcat(Cat):
    def speak(self):
        print("I'm a black cat.")
        
cat = Blackcat()
cat.speak()
super(Blackcat, cat).speak()

I'm a black cat.
I'm a cat.


In [31]:
import numpy as np
a = tf.constant(np.random.rand(4,))
b = tf.constant(np.random.rand(4,1))
print(a,b)

tf.Tensor([0.98654091 0.70102231 0.84872371 0.50446296], shape=(4,), dtype=float64) tf.Tensor(
[[0.5130213 ]
 [0.94787226]
 [0.04308714]
 [0.44236359]], shape=(4, 1), dtype=float64)
