In [1]:
import tensorflow as tf

In [2]:
tf.constant([[1,2,3,4],[5,6,7,8]])

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>

In [14]:
x = tf.constant(1.0)
with tf.GradientTape() as t:
    t.watch(x)
    y = x * x + tf.exp(x)

dy_dx = t.gradient(y, x)
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=4.7182817>

In [13]:
x = tf.constant(3.0)
with tf.GradientTape(persistent=True) as t:
  t.watch(x)
  y = x * x
  z = y * y
dz_dx = t.gradient(z, x)  # 108.0 (4*x^3 at x = 3)
dy_dx = t.gradient(y, x)  # 6.0
del t  # Drop the reference to the tape